{
 "title": "Services Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "metrics(.*_cluster_.*_upstream_rq_2xx)"
   },
   {
    "name": "destination",
    "query": "metrics(.*_cluster_.*_upstream_rq_2xx)"
   }
  ]
 },
 "panels": [
  {
   "title": "2XX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate([[source]]_cluster_[[destination]]_upstream_rq_2xx[1m])",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[source]]_cluster_[[destination]]_upstream_rq_5xx - [[source]]_cluster_[[destination]]_upstream_rq_5xx offset $__interval",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "[[source]]_cluster_[[destination]]_upstream_rq_time",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(latency_sum[5m])/rate(latency_count[5m])",
     "legendFormat": "{{service}} {{status}}"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "rate(counter[1m])", "legendFormat": "{{service}} - {{status}}" }
   ]
  }
 ]
}